export enum AvailableRoles {
    ADMIN = 'ROLE_ADMIN',
    DRIVER = 'ROLE_DRIVER',
    // ANDROID_BOT = 'ROLE_ANDROID_BOT',
    // SUPER_ADMIN = 'ROLE_SUPER_ADMIN',
    // DISPATCH_MANAGER = 'ROLE_DISPATCH_MANAGER',
    // ACCOUNT_MANAGER = 'ROLE_ACCOUNT_MANAGER',
    // SALES_MANAGER = 'ROLE_SALES_MANAGER',
    // PARTNER_ACCOUNT_OWNER = 'ROLE_PARTNER_ACCOUNT_OWNER',
    // CLIENT_ACCOUTN_OWNER = 'ROLE_CLIENT_ACCOUNT_OWNER',
    GUARDIAN = 'ROLE_GUARDIAN',
    CLIENT_ADMIN = 'ROLE_CLIENT_ADMIN',
}
